Default: &defaults
  database: ministeam.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: ministeam_test.sqlite3
  <<: *defaults

Staging:
  database: ministeam_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: ministeam_production.sqlite3
  poolsize: 100
  <<: *defaults
